name: Build and Deploy to RunPod

on:
  push:
    branches:
      - main  # or whichever branch you want

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & push Docker image
      run: docker buildx build --push --tag ${{ secrets.RUNPOD_IMAGE_NAME }} .

    - name: Resume RunPod pod
          run: |
            curl --request POST \
              --header 'content-type: application/json' \
              --url 'https://api.runpod.io/graphql?api_key=${{ secrets.RUNPOD_API_KEY }}' \
              --data '{"query": "mutation { podResume( input: { podId: \"${{ secrets.RUNPOD_POD_ID }}\", gpuCount: 1 } ) { id desiredStatus imageName env machineId machine { podHostId } } }"}'
